# Generated by Django 5.2.4 on 2025-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=6, verbose_name='Código de Verificação'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='codigo_verificacao_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Código'),
        ),
    ]
