# Generated by Django 5.2.4 on 2025-09-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_customuser_codigo_verificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tenant_id',
            field=models.IntegerField(blank=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='tenant_id',
            field=models.IntegerField(blank=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
        migrations.AddField(
            model_name='despesaparcelada',
            name='tenant_id',
            field=models.IntegerField(blank=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tenant_id',
            field=models.IntegerField(blank=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
    ]
