# Generated by Django 5.2.4 on 2025-09-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_categoria_tenant_id_conta_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cor',
            field=models.CharField(default='#007bff', help_text='Cor da conta em formato hexadecimal', max_length=7),
        ),
    ]
