# Generated by Django 5.2.4 on 2025-09-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaPlanejada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('tenant_id', models.IntegerField(blank=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True)),
                ('despesa_parcelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_planejadas', to='financas.despesaparcelada')),
                ('transacao_pagamento', models.ForeignKey(blank=True, help_text='Transação criada quando a parcela foi paga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.transacao')),
            ],
            options={
                'verbose_name': 'Parcela Planejada',
                'verbose_name_plural': 'Parcelas Planejadas',
                'ordering': ['numero_parcela'],
                'unique_together': {('despesa_parcelada', 'numero_parcela')},
            },
        ),
    ]
