# Generated by Django 5.2.4 on 2025-09-06 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_parcelas', models.IntegerField()),
                ('data_primeira_parcela', models.DateField()),
                ('dia_vencimento', models.IntegerField(default=1, help_text='Dia do mês para vencimento (1-31)')),
                ('intervalo_tipo', models.CharField(choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal'), ('personalizado', 'Personalizado (dias)')], default='mensal', max_length=15)),
                ('intervalo_dias', models.IntegerField(blank=True, help_text='Número de dias para intervalo personalizado', null=True)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcelas_geradas', models.BooleanField(default=False)),
                ('tenant_id', models.IntegerField(blank=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
                ('conta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.conta')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='conta_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.contareceber'),
        ),
    ]
