# Generated by Django 5.2.4 on 2025-09-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_contareceber_transacao_conta_receber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contareceber',
            options={'ordering': ['-criada_em']},
        ),
    ]
