# Generated by Django 5.2.4 on 2025-09-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_parcelaplanejada'),
        ('financas', '0007_alter_contareceber_options'),
    ]

    operations = [
    ]
