# Generated by Django 5.2.4 on 2025-09-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_merge_20250906_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='conta_receber',
        ),
        migrations.DeleteModel(
            name='ContaReceber',
        ),
    ]
