# Generated by Django 5.2.4 on 2025-09-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_remove_transacao_conta_receber_delete_contareceber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome', 'tenant_id')},
        ),
    ]
