# Generated by Django 5.2.4 on 2025-09-17 21:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_alter_categoria_nome_alter_categoria_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoFechamento',
        ),
        migrations.AlterModelOptions(
            name='fechamentomensal',
            options={'ordering': ['ano', 'mes', 'conta'], 'verbose_name': 'Fechamento Mensal', 'verbose_name_plural': 'Fechamentos Mensais'},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fechamentomensal',
            unique_together={('conta', 'mes', 'ano')},
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='ano',
            field=models.IntegerField(help_text='Ano do fechamento'),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, help_text='Data e hora do fechamento', null=True),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='data_fim_periodo',
            field=models.DateField(blank=True, help_text='Data de fim do período', null=True),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='data_inicio_periodo',
            field=models.DateField(blank=True, help_text='Data de início do período', null=True),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='fechado',
            field=models.BooleanField(default=True, help_text='Indica se o mês está fechado'),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='mes',
            field=models.IntegerField(help_text='Mês do fechamento (1-12)'),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo final do mês', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo inicial do mês', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='total_despesas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de despesas no mês', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='total_receitas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de receitas no mês', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='fechamentomensal',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='fechamentomensal',
            name='eh_parcial',
        ),
    ]
