# Generated by Django 5.2.4 on 2025-09-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0011_add_tenant_id_to_fechamentomensal'),
    ]

    operations = [
        # Remover a constraint unique_together da tabela Categoria
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        # Adicionar o campo tenant_id à tabela FechamentoMensal
        migrations.AddField(
            model_name='fechamentomensal',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
    ]
