# Generated by Django 5.2.4 on 2025-09-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0012_auto_20250917_1824'),
    ]

    operations = [
        # Remover o campo tenant_id duplicado da tabela FechamentoMensal
        migrations.RemoveField(
            model_name='fechamentomensal',
            name='tenant_id',
        ),
    ]
