# Generated by Django 5.2.4 on 2025-09-17 22:21

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0013_auto_20250917_1918'),
    ]

    operations = [
        # Não adicionar o campo tenant_id novamente, pois já existe na migração 0011
        # migrations.AddField(
        #     model_name='fechamentomensal',
        #     name='tenant_id',
        #     field=models.IntegerField(blank=True, db_index=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        # ),
    ]
