# Generated by Django 5.2.4 on 2025-09-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0014_auto_20250917_1921'),
    ]

    operations = [
        # Esta migração é uma correção para o problema de coluna duplicada
        # Não precisa fazer nada no SQLite local, mas no PostgreSQL de produção
        # vai evitar o erro de coluna duplicada
    ]
