# Generated by Django 5.2.4 on 2025-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0016_fix_tenant_id_postgres'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentomensal',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID do tenant (usuário) para isolamento de dados', null=True),
        ),
    ]
